Revert "Add resource initializer support (#6826)"
This is causing regression e2e tests to fail:

1) saved_model_v1_with_hashtable.
     #REGRESSION convert_predict webgl {"WEBGL_VERSION":2,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0}
     Error: Arrays differ: actual[0] = -1, expected[0] = 3.

To reproduce this, use node 16 in e2e/ and run `NIGHTLY=true ./scripts/test-ci.sh`, or, after running that to generate the required files, run `yarn karma start --tags '#REGRESSION'`.

This reverts commit 42dee166e0c8681c129d0c952dd7f9540e0ed4cb.