webgpu: Fix the compile error in conv2d_naive shader (#2002)
BUG

When switch to the naive method of conv2d, below error will be met:
Error: Shader compilation failed: file:124: error: 'getX' : no matching overloaded function found.
Error: Shader compilation failed: file:131: error: 'getW' : no matching overloaded function found.

The fixing uses the right get* methods. And uses int instead of uint as the parameter type.