"tensorflowjswizard" distribution does not exist
I'm guessing these instructions are outdated and I should just `pip install tensorflowjs`, because it seems to provide the `tensorflowjs_wizard` executable.

```
$ pip3 install tensorflowjswizard
ERROR: Could not find a version that satisfies the requirement tensorflowjswizard
ERROR: No matching distribution found for tensorflowjswizard
$ pip3 install tensorflowjs_wizard
ERROR: Could not find a version that satisfies the requirement tensorflowjs_wizard
ERROR: No matching distribution found for tensorflowjs_wizard
$ pip3 install tensorflowjs-wizard
ERROR: Could not find a version that satisfies the requirement tensorflowjs-wizard
ERROR: No matching distribution found for tensorflowjs-wizard
```