Cleanup changed binding.gyp rules and prevent error when running GPU (#272)
release.

This exception happens because we tag in the CPU tfjs-node release
script.
```
Error: Could not git tag with v1.2.3: Command failed: git tag v1.2.3
fatal: tag 'v1.2.3' already exists
```